### ISSUE TITLE
No firmware link

### ISSUE THREAD

**Issue by dunk2k** [Dwctor/Kaly#1]
`Readme.md` says "The firmware for the Kaly will be released sometime soon and will be linked here" yet no link is available nor can I find this keyboard in [qmk/qmk_firnware](https://github.com/qmk/qmk_firmware) Repo.

@Dwctor would you be able to oblige either a link to firmware, add firmware files in this repo, or create a PR in qmk/qmk_firmware for adding this keyboard to QMK repo?

**Comment by Dwctor** [comment]
I apologize for my tardiness in releasing the firmware. The faculty semester and projects caught up to me before I could read up on the QMK/Vial requirements to push code to them. The firmware is ready, but I didn't yet read their standards for commits. 

You can find it [here](https://drive.google.com/file/d/1a9VElT-ut_U5oVTil7RkMKWK1fT1-yMn/view?usp=drive_link). I'll keep this link up until I close this issue, which will happen when I get my firmware merged into any of the two repos (QMK or Vial). I'll take time to solve this in up to a week from now.

To use that link, clone the [Vial](https://github.com/vial-kb/vial-qmk) repository, place the Kaly folder of the link above into the keyboards folder of the Vial repo and flash it to your microcontroller with "make flash kaly/kaly42:vial:flash" after (setting up QMK)[https://docs.qmk.fm/#/newbs_getting_started].

Until firmware is released, anyone with issues can come to this issue thread and  @ me. I'll be here to help!

**Comment by Dwctor** [comment]
@dunk2k I have just added a [pull request](https://github.com/qmk/qmk_firmware/pull/22279) into the [QMK repo](https://github.com/qmk/qmk_firmware). I'll keep an eye on what the reviewers say and hopefully have this finished soon!

**Comment by Dwctor** [comment]
@dunk2k Just wanted to quickly drop by and thank you for all the help with this! You made the process almost effortless and I thank you for it.

**Comment by dunk2k** [comment]
@Dwctor 
Conversely, thanks for picking up the ball on this resulting in firmware being available to future Kaly adopters ☺️
