### ISSUE TITLE
Created the keyboard

### ISSUE THREAD

**Issue by tybaltgrey** [Dwctor/Kaly#2]
I made the keyboard! Here are a couple of pictures now I just need to figure out how to do the firmware.![image](https://github.com/Dwctor/Kaly/assets/39355378/07505ef1-98c5-4837-8fd3-21ea366289b9)

TechBeardNc@icloud.com

**Comment by Dwctor** [comment]
Really cool picture! To my knowledge, you are the first to make a Kaly42 with a non-black PCB! :D

As far as I've seen, most people ended up using the firmware I left over at qmk! You can just configure a layout for yourself at https://config.qmk.fm/#/kaly/kaly42/LAYOUT_split_3x6_3 

Just a pro-tip: remember not to unplug or plug the trrs cable between the halves when the type C is connected to the PC, as you can short the Blackpills.

May I use that picture in the future to promote the Kaly42? (Or at least leave a copy of it in the repo later?)

Thanks for building the Kaly42, I hope you enjoy using it as much as I enjoyed building it!

**Comment by tybaltgrey** [comment]
Sure man. I really appreciate you making this. I have bought the pieces over the past month to make it and yes, you can use the picture and if you want anymore no problem.

**Comment by tybaltgrey** [comment]
well, I flashed everything. The left side works. The right side doesn't even when it's connected alone. I can't get anything to happen even going back and flashing the default firmware from github.

**Comment by Dwctor** [comment]
@techbeardnc Could it be that your right side MCU is dead? Does it flash at all or do you find a problem with the flashing process?

**Comment by tybaltgrey** [comment]
No, it flash completely fine

**Comment by tybaltgrey** [comment]
Forgive me for being completely naïve to this, but I am too flash both sides, correct? I mean I did with my tweaked one, but when that didn't work, I went and got the default from the toolbox.

**Comment by tybaltgrey** [comment]
One last thing while it's on my mind, do you flash each side while it is connected to each other or separately? Is there a specific order you need to flash the haves?

**Comment by Dwctor** [comment]
As far as my knowledge goes, this is the way of doing it:

A. Get left side flashed (alone)
B. Get right side flashed (alone)
C. When updating, flashing left side only should work

After doing B, the right side if plugged into the PC alone should think it's the left side and work "inverted", but completely fine otherwise. If no keys come out, there's something weird. I am not sure there is a necessary order, it should not affect anything, I just do left first and right second out of habit.

**Comment by tybaltgrey** [comment]
You were right, the black pill was zapped. Used a spare, it works now.
