### ISSUE TITLE
Vial Firmware

### ISSUE THREAD

**Issue by aggregatedesign** [Dwctor/Kaly#3]
You mentioned the in the readme.md that if a Vial firmware was needed, feel free to contact you.  It would help, and be appreciated, if you could provide the vial firmware here or commit it to the vial repo.

**Comment by Dwctor** [comment]
Sadly, I don't have the time to set-up the Vial firmware in the moment. If you'd like help with this, please use my discord "dwctor", I'll give you an answer as soon as I have some free time!

If anyone is reading this issue in the future: The Vial firmware is a work in progress and I'll be adding it both to the repo and to the vial Github ASAP! I am just very busy at the moment.
